project:
  type: website

website:
  title: "INCT Drogas de abuso"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - equipe.qmd
      - publicacoes.qmd

format:
  html:
    theme:
      - instance
      - brand
    css: styles.css
    toc: true

lang: pt-BR

